#pragma once

#define LUMIGRID_VERSION_MAJOR 1
#define LUMIGRID_VERSION_MINOR 0
#define LUMIGRID_VERSION_PATCH 0
#define LUMIGRID_VERSION_STRING "1.0.0"
#define LUMIGRID_BUILD_DATE __DATE__
#define LUMIGRID_BUILD_TIME __TIME__
